[phases.setup]
nixPkgs = ['nodejs-22_x']

[phases.install]
cmds = ['corepack enable', 'corepack prepare pnpm@latest --activate', 'pnpm install']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'node dist/index.js'

